### ISSUE TITLE
Cannot open rendered word doc

### ISSUE THREAD

**Issue by chloecwh** [TWUOnline/phil210-GX-q#2]
[PHIL-210.docx](https://github.com/user-attachments/files/17420630/PHIL-210.docx)

Screenshot of error message:
<img width="251" alt="Screenshot 2024-10-17 at 11 29 16 AM" src="https://github.com/user-attachments/assets/eb0a7e0c-f171-4757-8c57-92e7a056860a">

**Comment by chloecwh** [comment]
I have enough storage and I'm able to open other rendered docs. So I think it's specific to this doc that might be corrupted?

**Comment by cmadland** [comment]
i can't open in Werd, but it opened for me in Apple Pages

Can you upload and open in O365?

**Comment by chloecwh** [comment]
Able to open on [Sharepoint](https://mytwu.sharepoint.com/:w:/s/LearningDesign/EdzkT9CAq_VGoosW6xi-qAwByHeUr3UPC4_mt-ZNKtYwuw?e=Btd4f9) but not on desktop. To use the macro splitting tool, I'll need to open it on desktop... 

<img width="1326" alt="Screenshot 2024-10-17 at 11 38 39 AM" src="https://github.com/user-attachments/assets/7bc717ae-fa0f-4dbb-9d72-63fda4ccde13">

**Comment by Jeff-TWU** [comment]
So I was able to copy and paste into a new doc... however it doesn't keep track of the headings for whatever reason, so can't be split unless you manually change them. Which isn't such a big deal, but a little annoying.

**Comment by chloecwh** [comment]
Sounds good, thanks for the input!
